name: Deploy Backend Lambda

on:
  push:
    paths:
      - "backend/process-uploaded-file/**"
    branches:
      - main

env:
  AWS_REGION: us-east-1
  LAMBDA_FUNCTION_NAME: ${{ secrets.LAMBDA_FUNCTION_NAME }}

jobs:
  deploy:
    name: Update Lambda Function
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Zip Lambda function code
        run: |
          cd backend/process-uploaded-file
          zip -r lambda.zip .

      - name: Update Lambda code
        run: |
          aws lambda update-function-code \
            --function-name ${{ env.LAMBDA_FUNCTION_NAME }} \
            --zip-file fileb://backend/process-uploaded-file/lambda.zip