name: Terraform Deploy

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-1
  TF_VAR_upload_bucket_name: ${{ secrets.UPLOAD_BUCKET_NAME }}
  TF_VAR_aws_region: us-east-1

jobs:
  terraform:
    name: Terraform Apply
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: infra/terraform

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init (Reconfigure)
        run: terraform init -reconfigure


      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        env:
          GZIP: "false"
        run: terraform apply -auto-approve
